#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2026 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.5.1
# Product:       sbn4x
# Model-Version: 2.0.0
#

import pytest
from sensirion_i2c_sbn4x.device import Sbn4xDevice


@pytest.fixture
def sensor(channel_provider):
    channel_provider.i2c_frequency = 100e3
    channel_provider.supply_voltage = 5.0
    with channel_provider:
        channel = channel_provider.get_channel(slave_address=0x20,
                                               crc_parameters=(8, 0x31, 0xff, 0x0))
        yield Sbn4xDevice(channel)


def test_get_serial_number1(sensor):
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )


def test_get_article_code1(sensor):
    article_code = sensor.get_article_code()
    print(f"article_code: {article_code}; "
          )


def test_get_product_name1(sensor):
    product_name = sensor.get_product_name()
    print(f"product_name: {product_name}; "
          )


def test_get_product_type1(sensor):
    product_type = sensor.get_product_type()
    print(f"product_type: {product_type}; "
          )


def test_get_version1(sensor):
    (firmware_major, firmware_minor, firmware_develop_flag, hardware_major, hardware_minor, protocol_major, protocol_minor,
     padding
     ) = sensor.get_version()
    print(f"firmware_major: {firmware_major}; "
          f"firmware_minor: {firmware_minor}; "
          f"firmware_develop_flag: {firmware_develop_flag}; "
          f"hardware_major: {hardware_major}; "
          f"hardware_minor: {hardware_minor}; "
          f"protocol_major: {protocol_major}; "
          f"protocol_minor: {protocol_minor}; "
          f"padding: {padding}; "
          )


def test_get_device_uid1(sensor):
    device_uid = sensor.get_device_uid()
    print(f"device_uid: {device_uid}; "
          )


def test_read_device_status1(sensor):
    device_status = sensor.read_device_status()
    print(f"device_status: {device_status}; "
          )


def test_read_and_clear_device_status1(sensor):
    device_status = sensor.read_and_clear_device_status()
    print(f"device_status: {device_status}; "
          )


def test_start_periodic_measurement_mode1(sensor):
    sensor.start_periodic_measurement_mode(30000)
    device_status = sensor.read_device_status()
    print(f"device_status: {device_status}; "
          )
    device_status = sensor.read_and_clear_device_status()
    print(f"device_status: {device_status}; "
          )
    (measurement_counter, o2_dry_percent, co2_dry_percent, respiratory_exchange_ratio, pressure
     ) = sensor.read_measurements()
    print(f"measurement_counter: {measurement_counter}; "
          f"o2_dry_percent: {o2_dry_percent}; "
          f"co2_dry_percent: {co2_dry_percent}; "
          f"respiratory_exchange_ratio: {respiratory_exchange_ratio}; "
          f"pressure: {pressure}; "
          )
    sensor.stop_measurement()

