#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.3.4
# Product:       sbn4x
# Model-Version: 1.0.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sbn4x.device import Sbn4xDevice

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x20,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sbn4xDevice(channel)
    product_name = sensor.get_product_name()
    print(f"product_name: {product_name}; "
          )
    product_type = sensor.get_product_type()
    print(f"product_type: {product_type}; "
          )
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )
    sensor.start_periodic_measurement_mode(30000)
    time.sleep(0.2)
    for i in range(10):
        try:
            (measurement_counter, o2_dry_percent, co2_dry_percent, pressure, o2_partial_pressure, h2o_partial_pressure,
             temperature, relative_humidity, flags
             ) = sensor.read_measurements()
            print(f"measurement_counter: {measurement_counter}; "
                  f"o2_dry_percent: {o2_dry_percent}; "
                  f"co2_dry_percent: {co2_dry_percent}; "
                  f"pressure: {pressure}; "
                  f"o2_partial_pressure: {o2_partial_pressure}; "
                  f"h2o_partial_pressure: {h2o_partial_pressure}; "
                  f"temperature: {temperature}; "
                  f"relative_humidity: {relative_humidity}; "
                  f"flags: {flags}; "
                  )
        except BaseException:
            ...
    sensor.stop_measurement()
